server:
  port: 8081
  servlet:
    context-path: /api
management:
  endpoint:
    health:
      show-details: always
spring:
  data:
    mongodb:
      uri: ${DB_URL}
  jackson:
    default-property-inclusion: non_null
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    username: ${smtp_user}
    password: ${smtp_password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
jwt:
  secret : ${JWT_SECRET}