server:
  port: 8081
  servlet:
    context-path: /api
management:
  endpoint:
    health:
      show-details: always
spring:
  data:
    mongodb:
      uri: mongodb://tom:jerry@localhost:28001/footballdb?authSource=admin

